<a href="https://colab.research.google.com/github/ersawant/100-ds-problems/blob/master/00_Keras_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# Keras Basics

Welcome to the section on deep learning! We'll be using Keras with a TensorFlow backend to perform our deep learning operations.

This means we should get familiar with some Keras fundamentals and basics!

## Imports



In [0]:
import numpy as np

## Dataset

We will use the famous Iris Data set.
_____
More info on the data set:
https://en.wikipedia.org/wiki/Iris_flower_data_set

## Reading in the Data Set

We've already downloaded the dataset, its in this folder. So let's open it up. 

In [0]:
from sklearn.datasets import load_iris

In [0]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [0]:
X = iris.data

In [7]:
from IPython.display import Image
Image("iris.png")

In [14]:
X[1]

array([4.9, 3. , 1.4, 0.2])

In [0]:
y = iris.target

In [0]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [0]:
y = to_categorical(y)

In [18]:
y.shape

(150, 3)

In [20]:
y[0]

array([1., 0., 0.], dtype=float32)

## Split the Data into Training and Test

Its time to split the data into a train/test set. Keep in mind, sometimes people like to split 3 ways, train/test/validation. We'll keep things simple for now. **Remember to check out the video explanation as to why we split and what all the parameters mean!**

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [31]:
X_train.shape

(100, 4)

In [30]:
X_test[0]

array([6.1, 2.8, 4.7, 1.2])

In [32]:
y_train.shape


(100, 3)

In [33]:
y_test.shape

(50, 3)

## Standardizing the Data

Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

The scikit learn library also provides a nice function for this.

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [0]:
from sklearn.preprocessing import MinMaxScaler

In [0]:
scaler_object = MinMaxScaler()

In [36]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [0]:
scaled_X_train = scaler_object.transform(X_train)

In [0]:
scaled_X_test = scaler_object.transform(X_test)

Ok, now we have the data scaled!

In [39]:
X_train.max()

7.7

In [40]:
scaled_X_train.max()

1.0

In [43]:
X_train[0]

array([5.7, 2.9, 4.2, 1.3])

In [44]:
scaled_X_train[0]

array([0.41176471, 0.40909091, 0.55357143, 0.5       ])

## Building the Network with Keras

Let's build a simple neural network!

In [0]:
from keras.models import Sequential
from keras.layers import Dense

In [0]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))

In [0]:

model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [63]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 12        
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 12        
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 12        
_________________________________________________________________
dense_10 (Dense)             (None, 3)                 12        
__________

## Fit (Train) the Model

In [64]:
# Play around with number of epochs as well!
model.fit(scaled_X_train,y_train,epochs=150, verbose=2)

Epoch 1/150
 - 1s - loss: 1.1435 - acc: 0.3500
Epoch 2/150
 - 0s - loss: 1.1421 - acc: 0.3500
Epoch 3/150
 - 0s - loss: 1.1404 - acc: 0.3500
Epoch 4/150
 - 0s - loss: 1.1392 - acc: 0.3500
Epoch 5/150
 - 0s - loss: 1.1379 - acc: 0.3500
Epoch 6/150
 - 0s - loss: 1.1367 - acc: 0.3500
Epoch 7/150
 - 0s - loss: 1.1355 - acc: 0.3500
Epoch 8/150
 - 0s - loss: 1.1343 - acc: 0.3500
Epoch 9/150
 - 0s - loss: 1.1329 - acc: 0.3500
Epoch 10/150
 - 0s - loss: 1.1318 - acc: 0.3500
Epoch 11/150
 - 0s - loss: 1.1303 - acc: 0.3500
Epoch 12/150
 - 0s - loss: 1.1290 - acc: 0.3500
Epoch 13/150
 - 0s - loss: 1.1277 - acc: 0.3500
Epoch 14/150
 - 0s - loss: 1.1267 - acc: 0.3500
Epoch 15/150
 - 0s - loss: 1.1255 - acc: 0.3500
Epoch 16/150
 - 0s - loss: 1.1240 - acc: 0.3500
Epoch 17/150
 - 0s - loss: 1.1226 - acc: 0.3500
Epoch 18/150
 - 0s - loss: 1.1214 - acc: 0.3500
Epoch 19/150
 - 0s - loss: 1.1202 - acc: 0.3500
Epoch 20/150
 - 0s - loss: 1.1192 - acc: 0.3500
Epoch 21/150
 - 0s - loss: 1.1179 - acc: 0.3500
E

## Predicting New Unseen Data

Let's see how we did by predicting on **new data**. Remember, our model has **never** seen the test data that we scaled previously! This process is the exact same process you would use on totally brand new data. For example , a brand new bank note that you just analyzed .

In [66]:
scaled_X_test[0]

array([0.52941176, 0.36363636, 0.64285714, 0.45833333])

In [0]:
# Spits out probabilities by default.
# model.predict(scaled_X_test)

In [68]:
model.predict_classes(scaled_X_test)

array([1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1,
       2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2,
       2, 1, 1, 1, 1, 1])

# Evaluating Model Performance

So how well did we do? How do we actually measure "well". Is 95% accuracy good enough? It all depends on the situation. Also we need to take into account things like recall and precision. Make sure to watch the video discussion on classification evaluation before running this code!

In [69]:
model.metrics_names

['loss', 'acc']

In [70]:
model.evaluate(x=scaled_X_test,y=y_test)

50/50 [==============================] - 0s 3ms/step


[1.0868086624145508, 0.3000000035762787]

In [0]:
from sklearn.metrics import confusion_matrix,classification_report

In [0]:
predictions = model.predict_classes(scaled_X_test)

In [73]:
predictions

array([1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1,
       2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2,
       2, 1, 1, 1, 1, 1])

In [76]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [77]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[ 0,  0, 19],
       [ 0, 15,  0],
       [ 0, 16,  0]])

In [85]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.48      1.00      0.65        15
           2       0.00      0.00      0.00        16

   micro avg       0.30      0.30      0.30        50
   macro avg       0.16      0.33      0.22        50
weighted avg       0.15      0.30      0.20        50



## Saving and Loading Models

Now that we have a model trained, let's see how we can save and load it.

In [0]:
model.save('myfirstmodel.h5')

In [0]:
from keras.models import load_model

In [0]:
newmodel = load_model('myfirstmodel.h5')

In [89]:
newmodel.predict_classes(X_test)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [90]:
from IPython.display import Image
Image("nn-iris.png")

Great job! You now know how to preprocess data, train a neural network, and evaluate its classification performance!